# Generated by Django 4.2.7 on 2023-11-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabrikaImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='fabrikapic/')),
            ],
        ),
        migrations.CreateModel(
            name='FuarImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='fuarpic/')),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('kategoriResim', models.FileField(upload_to='kategoripic/')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('backImage', models.FileField(upload_to='backgroundkategoripic/')),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urunKodu', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('urunResim', models.FileField(upload_to='urunpic/')),
                ('kanat', models.TextField(max_length=2000)),
                ('kasa', models.TextField(max_length=2000)),
                ('pervaz', models.TextField(max_length=2000)),
                ('cila', models.TextField(blank=True, max_length=2000, null=True)),
                ('boya', models.TextField(blank=True, max_length=2000, null=True)),
                ('urunKategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.kategori')),
            ],
        ),
    ]
