# Generated by Django 4.2.7 on 2023-11-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='isim_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='isim_tr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='boya_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='boya_tr',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='cila_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='cila_tr',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='kanat_en',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='kanat_tr',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='kasa_en',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='kasa_tr',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='pervaz_en',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='pervaz_tr',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='urunKodu_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='urunKodu_tr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
